#pragma once

#include "Counters.h"

#include "../Traversal/RayPacket.h"
#include "../Traversal/HitPoint.h"

#include "../Color/RayColor.h"

#include "../Math/Random.h"

namespace rt {

struct PathDebugData;

class GenericSampler;
class Camera;
class IRendererContext;
using RendererContextPtr = std::unique_ptr<IRendererContext>;

enum class TraversalMode : Uint8
{
    Single = 0,
    Packet,
};

struct AdaptiveRenderingSettings
{
    bool enable = false;
    Uint32 numInitialPasses = 10;
    Uint32 minBlockSize = 4;
    Uint32 maxBlockSize = 256;
    float subdivisionTreshold = 0.005f;
    float convergenceTreshold = 0.0001f;
};

struct RenderingParams
{
    Uint32 numThreads = 0;

    // Number of sample dimensions generated by low-discrepancy sampler
    // Note: If more dimensions is required during integration, random samples will be used
    Uint32 sampleDimensions = 64;

    // Antialiasing factor
    // Setting to higher values will blur the image
    float antiAliasingSpread = 0.5f;

    // Motion blur multiplier
    // NOTE: must be in [0...1] range
    float motionBlurStrength = 0.5f;

    // maximum ray depth
    Uint32 maxRayDepth = 20;

    // ray depth at which Russian Roulette algorithm kicks in
    Uint32 minRussianRouletteDepth = 1;

    // rendering tile dimensions (tiles are processed as a tasks in thread pool in parallel)
    Uint16 tileSize = 16;

    // select mode of ray traversal
    TraversalMode traversalMode = TraversalMode::Packet;

    // adaptive rendering settings
    AdaptiveRenderingSettings adaptiveSettings;
};

struct PixelBreakpoint
{
    Uint32 x = UINT32_MAX;
    Uint32 y = UINT32_MAX;
};

/**
 * A structure with local (per-thread) data.
 * It's like a hub for all global params (read only) and local state (read write).
 */
struct RT_ALIGN(64) RenderingContext
    : public Aligned<64>
    , public NoCopyable
{
    RAYLIB_API RenderingContext();

    const Camera* camera = nullptr;

    Wavelength wavelength;

    GenericSampler* sampler = nullptr;

    // per-thread pseudo-random number generator
    math::Random randomGenerator;

    // renderer-specific context, can be null
    RendererContextPtr rendererContext;

    // global rendering parameters
    const RenderingParams* params = nullptr;

    // per-thread counters
    RayTracingCounters counters;

    // counters used in local ray traversal routines
    LocalCounters localCounters;

    // for motion blur sampling
    float time = 0.0f;

    // optional path debugging data
    PathDebugData* pathDebugData = nullptr;

    PixelBreakpoint pixelBreakpoint;

    RayPacket rayPacket;

    HitPoint hitPoints[MaxRayPacketSize];

    // TODO separate stacks for scene and mesh
    Uint8 activeRaysMask[RayPacket::MaxNumGroups];
    Uint16 activeGroupsIndices[RayPacket::MaxNumGroups];
};


} // namespace rt
